report

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -59,6 +59,15 @@ jobs:
       run: |
         git push origin $TAG
 
+    # cleanup
+    - name: cleanup
+      run: |
+        docker compose down -v
+        docker rm -f $(docker ps -aq) || true
+        docker  image rm $(docker image ls -aq) || true
+        
+
+
     # - name: Github login
     #   if: github.ref == 'refs/heads/master'
     #   uses: actions/checkout@v3
@@ -83,32 +92,32 @@ jobs:
     #     git push origin master
 
 
-    # # report
-    # - name: failure
-    #   if: failure()
-    #   env:
-    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-    #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-    #   run: |
-    #     message="<b>❌ CI for branch:</b> $GITHUB_REF_NAME failed 🚨💀
-    #      <b>Tag:</b> $TAG
-    #      <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
-    #      <b>Run number:</b> $GITHUB_RUN_NUMBER"
+    # report
+    - name: failure
+      if: failure()
+      env:
+        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+      run: |
+        message="<b>❌ CI for branch:</b> $GITHUB_REF_NAME failed 🚨💀
+         <b>Tag:</b> $TAG
+         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
+         <b>Run number:</b> $GITHUB_RUN_NUMBER"
 
-    #     curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null
+        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null
 
 
-    # - name: success
-    #   if: success()
-    #   env:
-    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-    #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-    #   run: |
-    #     message="<b>✅ CI for branch:</b> $GITHUB_REF_NAME succeeded 🚀🤘
-    #      <b>Tag:</b> $TAG
-    #      <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
-    #      <b>Run number:</b> $GITHUB_RUN_NUMBER"
+    - name: success
+      if: success()
+      env:
+        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+      run: |
+        message="<b>✅ CI for branch:</b> $GITHUB_REF_NAME succeeded 🚀🤘
+         <b>Tag:</b> $TAG
+         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
+         <b>Run number:</b> $GITHUB_RUN_NUMBER"
 
-    #     curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null
+        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null
 
 
